# Generated by Django 2.0.2 on 2018-05-16 10:45

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('alignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score1', models.FloatField(blank=True, null=True)),
                ('report', models.CharField(blank=True, max_length=300, null=True)),
                ('is_current', models.NullBooleanField()),
                ('score2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'alignment',
            },
        ),
        migrations.CreateModel(
            name='AlignmentRun',
            fields=[
                ('alignment_run_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userstamp', models.CharField(blank=True, max_length=30, null=True)),
                ('time_run', models.DateTimeField(blank=True, null=True)),
                ('score1_type', models.CharField(blank=True, max_length=30, null=True)),
                ('report_type', models.CharField(blank=True, max_length=30, null=True)),
                ('pipeline_name', models.CharField(max_length=30)),
                ('pipeline_comment', models.CharField(max_length=300)),
                ('ensembl_release', models.BigIntegerField()),
                ('uniprot_file_swissprot', models.CharField(blank=True, max_length=300, null=True)),
                ('uniprot_file_isoform', models.CharField(blank=True, max_length=300, null=True)),
                ('uniprot_dir_trembl', models.CharField(blank=True, max_length=300, null=True)),
                ('logfile_dir', models.CharField(blank=True, max_length=300, null=True)),
                ('pipeline_script', models.CharField(max_length=300)),
                ('score2_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'alignment_run',
            },
        ),
        migrations.CreateModel(
            name='CvEntryType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'cv_entry_type',
            },
        ),
        migrations.CreateModel(
            name='CvUeLabel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'cv_ue_label',
            },
        ),
        migrations.CreateModel(
            name='CvUeStatus',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'cv_ue_status',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start', models.BigIntegerField(blank=True, null=True)),
                ('end', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='EnsemblGene',
            fields=[
                ('gene_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ensg_id', models.CharField(blank=True, max_length=30, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=30, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=50, null=True)),
                ('region_accession', models.CharField(blank=True, max_length=50, null=True)),
                ('mod_id', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.NullBooleanField()),
                ('seq_region_start', models.BigIntegerField(blank=True, null=True)),
                ('seq_region_end', models.BigIntegerField(blank=True, null=True)),
                ('seq_region_strand', models.BigIntegerField(blank=True, null=True)),
                ('biotype', models.CharField(blank=True, max_length=40, null=True)),
                ('time_loaded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ensembl_gene',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='EnsemblSpeciesHistory',
            fields=[
                ('ensembl_species_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(blank=True, max_length=30, null=True)),
                ('assembly_accession', models.CharField(blank=True, max_length=30, null=True)),
                ('ensembl_tax_id', models.BigIntegerField(blank=True, null=True)),
                ('ensembl_release', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('time_loaded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ensembl_species_history',
            },
        ),
        migrations.CreateModel(
            name='EnsemblTranscript',
            fields=[
                ('transcript_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enst_id', models.CharField(blank=True, max_length=30, null=True)),
                ('enst_version', models.SmallIntegerField(blank=True, null=True)),
                ('ccds_id', models.CharField(blank=True, max_length=30, null=True)),
                ('uniparc_accession', models.CharField(blank=True, max_length=30, null=True)),
                ('biotype', models.CharField(blank=True, max_length=40, null=True)),
                ('deleted', models.NullBooleanField()),
                ('seq_region_start', models.BigIntegerField(blank=True, null=True)),
                ('seq_region_end', models.BigIntegerField(blank=True, null=True)),
                ('supporting_evidence', models.CharField(blank=True, max_length=45, null=True)),
                ('userstamp', models.CharField(blank=True, max_length=30, null=True)),
                ('time_loaded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ensembl_transcript',
            },
        ),
        migrations.CreateModel(
            name='EnsemblUniprot',
            fields=[
                ('mapping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userstamp', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('mapping_history_id', models.BigIntegerField(blank=True, null=True)),
                ('sp_ensembl_mapping_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ensembl_uniprot',
            },
        ),
        migrations.CreateModel(
            name='EnspUCigar',
            fields=[
                ('ensp_u_cigar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cigarplus', models.TextField(blank=True, null=True)),
                ('mdz', models.TextField(blank=True, null=True)),
                ('uniprot_acc', models.CharField(max_length=30)),
                ('uniprot_seq_version', models.SmallIntegerField()),
                ('ensp_id', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'ensp_u_cigar',
            },
        ),
        migrations.CreateModel(
            name='GeneName',
            fields=[
                ('gene_name_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(blank=True, max_length=45, null=True)),
                ('gene_name_type_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'gene_name',
            },
        ),
        migrations.CreateModel(
            name='Isoform',
            fields=[
                ('isoform_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(blank=True, max_length=30, null=True)),
                ('sequence', models.CharField(blank=True, max_length=200, null=True)),
                ('uniparc_accession', models.CharField(blank=True, max_length=30, null=True)),
                ('embl_acc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'isoform',
            },
        ),
        migrations.CreateModel(
            name='MappingHistory',
            fields=[
                ('mapping_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ensembl_species_history_id', models.BigIntegerField(blank=True, null=True)),
                ('time_mapped', models.DateTimeField()),
                ('entries_mapped', models.BigIntegerField(blank=True, null=True)),
                ('entries_unmapped', models.BigIntegerField(blank=True, null=True)),
                ('uniprot_release', models.CharField(blank=True, max_length=7, null=True)),
                ('uniprot_taxid', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'mapping_history',
            },
        ),
        migrations.CreateModel(
            name='PdbEns',
            fields=[
                ('pdb_ens_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdb_acc', models.CharField(max_length=45)),
                ('pdb_release', models.CharField(max_length=11)),
                ('uniprot_acc', models.CharField(max_length=30)),
                ('enst_id', models.CharField(max_length=30)),
                ('enst_version', models.BigIntegerField(blank=True, null=True)),
                ('ensp_id', models.CharField(max_length=30)),
                ('ensp_start', models.BigIntegerField(blank=True, null=True)),
                ('ensp_end', models.BigIntegerField(blank=True, null=True)),
                ('pdb_start', models.BigIntegerField(blank=True, null=True)),
                ('pdb_end', models.BigIntegerField(blank=True, null=True)),
                ('pdb_chain', models.CharField(max_length=6)),
            ],
            options={
                'managed': False,
                'db_table': 'pdb_ens',
            },
        ),
        migrations.CreateModel(
            name='Ptm',
            fields=[
                ('ptm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('start', models.BigIntegerField(blank=True, null=True)),
                ('end', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ptm',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyMapping',
            fields=[
                ('taxonomy_mapping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ensembl_tax_id', models.BigIntegerField(blank=True, null=True)),
                ('uniprot_tax_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'taxonomy_mapping',
            },
        ),
        migrations.CreateModel(
            name='UeMappingComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uniprot_acc', models.CharField(max_length=30)),
                ('enst_id', models.CharField(max_length=30)),
                ('time_stamp', models.DateTimeField()),
                ('user_stamp', models.CharField(max_length=20)),
                ('comment', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'ue_mapping_comment',
            },
        ),
        migrations.CreateModel(
            name='UeMappingLabel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uniprot_acc', models.CharField(max_length=30)),
                ('enst_id', models.CharField(max_length=30)),
                ('time_stamp', models.DateTimeField()),
                ('user_stamp', models.CharField(max_length=20)),
                ('label', models.BigIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'ue_mapping_label',
            },
        ),
        migrations.CreateModel(
            name='UeMappingStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uniprot_acc', models.CharField(max_length=30)),
                ('enst_id', models.CharField(max_length=30)),
                ('time_stamp', models.DateTimeField()),
                ('user_stamp', models.CharField(max_length=20)),
                ('status', models.BigIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'ue_mapping_status',
            },
        ),
        migrations.CreateModel(
            name='Uniprot',
            fields=[
                ('uniprot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uniprot_acc', models.CharField(blank=True, max_length=30, null=True)),
                ('protein_existence_id', models.BigIntegerField(blank=True, null=True)),
                ('species', models.CharField(blank=True, max_length=30, null=True)),
                ('uniprot_tax_id', models.BigIntegerField(blank=True, null=True)),
                ('ensembl_derived', models.NullBooleanField()),
                ('is_isoform', models.NullBooleanField()),
                ('entry_type', models.CharField(blank=True, max_length=30, null=True)),
                ('release_version', models.CharField(blank=True, max_length=30, null=True)),
                ('userstamp', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('entry_version', models.BigIntegerField(blank=True, null=True)),
                ('mapping_history_id', models.BigIntegerField(blank=True, null=True)),
                ('sequence_version', models.SmallIntegerField(blank=True, null=True)),
                ('is_canonical', models.BigIntegerField(blank=True, null=True)),
                ('upi', models.CharField(blank=True, max_length=13, null=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
                ('canonical_accession', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'uniprot',
            },
        ),
        migrations.CreateModel(
            name='UniprotEntry',
            fields=[
                ('uniprot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uniprot_acc', models.CharField(blank=True, max_length=30, null=True)),
                ('uniprot_tax_id', models.BigIntegerField(blank=True, null=True)),
                ('userstamp', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('sequence_version', models.SmallIntegerField(blank=True, null=True)),
                ('upi', models.CharField(blank=True, max_length=13, null=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'uniprot_entry',
            },
        ),
        migrations.CreateModel(
            name='UniprotEntryHistory',
            fields=[
                ('uniprot_entry_version_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('release_version', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'uniprot_entry_history',
            },
        ),
        migrations.CreateModel(
            name='UniprotEntryVersion',
            fields=[
                ('uniprot_entry_version_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('protein_existence_id', models.BigIntegerField(blank=True, null=True)),
                ('ensembl_derived', models.NullBooleanField()),
                ('is_isoform', models.NullBooleanField()),
                ('entry_type', models.CharField(blank=True, max_length=30, null=True)),
                ('userstamp', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('entry_version', models.BigIntegerField(blank=True, null=True)),
                ('is_canonical', models.BigIntegerField(blank=True, null=True)),
                ('canonical_accession', models.CharField(blank=True, max_length=30, null=True)),
                ('uniprot_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'uniprot_entry_version',
            },
        ),
        migrations.CreateModel(
            name='UniprotUnmapped',
            fields=[
                ('uniprot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uniprot_acc', models.CharField(blank=True, max_length=30, null=True)),
                ('protein_existence_id', models.BigIntegerField(blank=True, null=True)),
                ('species', models.CharField(blank=True, max_length=30, null=True)),
                ('uniprot_tax_id', models.BigIntegerField(blank=True, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=30, null=True)),
                ('release_version', models.CharField(blank=True, max_length=30, null=True)),
                ('userstamp', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('entry_version', models.BigIntegerField(blank=True, null=True)),
                ('mapping_history_id', models.BigIntegerField(blank=True, null=True)),
                ('sequence_version', models.SmallIntegerField(blank=True, null=True)),
                ('upi', models.CharField(blank=True, max_length=13, null=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'uniprot_unmapped',
            },
        ),
        migrations.CreateModel(
            name='GeneHistory',
            fields=[
                ('ensembl_species_history', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='restui.EnsemblSpeciesHistory')),
            ],
            options={
                'managed': False,
                'db_table': 'gene_history',
            },
        ),
    ]
